# Generated by Django 4.2.25 on 2025-10-22 09:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LocationCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("user_longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "is_inside",
                    models.BooleanField(help_text="Was user inside geofence?"),
                ),
                (
                    "distance_meters",
                    models.FloatField(
                        help_text="Distance from geofence center in meters"
                    ),
                ),
                (
                    "geofence_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "geofence_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("geofence_radius", models.IntegerField()),
                ("user_agent", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Location Check",
                "verbose_name_plural": "Location Checks",
                "ordering": ["-checked_at"],
                "indexes": [
                    models.Index(
                        fields=["-checked_at"], name="geolocation_checked_00a0ce_idx"
                    ),
                    models.Index(
                        fields=["is_inside", "-checked_at"],
                        name="geolocation_is_insi_fe3c4b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GeofenceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location_name",
                    models.CharField(
                        default="XCLV Club Davao",
                        help_text="Name of the geofenced location",
                        max_length=255,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=7.093504776789317,
                        help_text="Latitude of the geofenced location",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        default=125.61290047486922,
                        help_text="Longitude of the geofenced location",
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ],
                    ),
                ),
                (
                    "radius_meters",
                    models.PositiveIntegerField(
                        default=50, help_text="Radius in meters for the geofenced area"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="geofence_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Geofence Settings",
                "verbose_name_plural": "Geofence Settings",
            },
        ),
    ]
