# Generated by Django 4.2.25 on 2025-10-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geolocation", "0002_alter_geofencesettings_radius_meters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="geofencesettings",
            name="radius_meters",
            field=models.PositiveIntegerField(
                default=2500, help_text="Radius in meters for the geofenced area"
            ),
        ),
    ]
