# Generated by Django 5.2.7 on 2025-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geolocation', '0003_alter_geofencesettings_radius_meters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geofencesettings',
            name='radius_meters',
            field=models.PositiveIntegerField(default=20000, help_text='Radius in meters for the geofenced area'),
        ),
    ]
