# Generated by Django 5.2.7 on 2025-10-31 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_order',
        ),
        migrations.AddField(
            model_name='table',
            name='table_status',
            field=models.CharField(default='available', max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='total_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='order_status',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.table'),
        ),
    ]
