# Generated by Django 5.2.7 on 2025-10-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_table_table_order_table_table_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='table_status',
            field=models.BooleanField(default=True),
        ),
    ]
