# Generated by Django 5.2.7 on 2025-10-31 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_alter_table_table_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableorder',
            name='order',
        ),
    ]
