# Generated by Django 4.2.25 on 2025-11-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0004_remove_tableorder_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="table",
            name="table_status",
            field=models.BooleanField(default=False),
        ),
    ]
