# Generated by Django 5.2.7 on 2025-11-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_alter_table_table_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='total_order_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tableorder',
            name='order_status',
            field=models.CharField(default='Pending', max_length=255),
        ),
    ]
