# Generated by Django 5.2.7 on 2025-12-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_tableorder_total_order_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='table_id_number',
        ),
        migrations.RemoveField(
            model_name='tableorder',
            name='table_order_id',
        ),
    ]
