# Generated by Django 4.2.25 on 2025-10-22 09:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QRBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_ID",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("batch_name", models.CharField(max_length=16, unique=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one batch can be active at a time",
                    ),
                ),
            ],
            options={
                "verbose_name": "QR Code Batch",
                "verbose_name_plural": "QR Code Batches",
                "ordering": ["-batch_name"],
            },
        ),
        migrations.CreateModel(
            name="QRCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_token", models.CharField(max_length=255, unique=True)),
                (
                    "table_type",
                    models.CharField(
                        blank=True,
                        choices=[("vvip", "VVIP"), ("vip", "VIP"), ("st", "Standard")],
                        help_text="Type of table this QR represents",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "table_number",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Table number within the type (1, 2, 3, etc.)",
                        null=True,
                    ),
                ),
                (
                    "qr_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Pre-generated static hash used in QR code URLs",
                        max_length=64,
                        null=True,
                        unique=True,
                    ),
                ),
                ("image", models.ImageField(upload_to="qrcodes/")),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qr_codes",
                        to="qr_codes.qrbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ValidationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qr_hash_attempted",
                    models.CharField(
                        help_text="The QR hash that was attempted", max_length=64
                    ),
                ),
                (
                    "user_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "user_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_from_club",
                    models.FloatField(
                        blank=True,
                        help_text="Distance in meters from club location",
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("success", "Success - Valid QR & Location"),
                            ("qr_not_found", "QR Hash Not Found"),
                            ("batch_inactive", "Batch Not Currently Active"),
                            ("location_invalid", "Location Outside Geofence"),
                            ("location_error", "Location Service Error"),
                            ("location_denied", "User Denied Location Permission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Detailed error message if validation failed",
                    ),
                ),
                ("user_agent", models.TextField(blank=True)),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Django session key for tracking user flow",
                        max_length=40,
                    ),
                ),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "qr_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validation_attempts",
                        to="qr_codes.qrcode",
                    ),
                ),
            ],
            options={
                "verbose_name": "Validation Attempt",
                "verbose_name_plural": "Validation Attempts",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["-attempted_at"], name="qr_codes_va_attempt_f6ffec_idx"
                    ),
                    models.Index(
                        fields=["result", "-attempted_at"],
                        name="qr_codes_va_result_65ccc4_idx",
                    ),
                    models.Index(
                        fields=["qr_code", "-attempted_at"],
                        name="qr_codes_va_qr_code_54156e_idx",
                    ),
                ],
            },
        ),
    ]
