# Generated by Django 5.2.7 on 2025-10-21 14:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchID', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batchName', models.CharField(max_length=16, unique=True)),
                ('batchStatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvalidList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValidList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_token', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='qrcodes/')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='qr_codes.batch')),
            ],
        ),
    ]
