# Generated by Django 4.2.25 on 2025-10-22 09:51

# In the new migration file
from django.db import migrations
from django.conf import settings
import hashlib
import os
import re

def create_qr_codes_from_media(apps, schema_editor):
    QRCode = apps.get_model('qr_codes', 'QRCode')
    QRBatch = apps.get_model('qr_codes', 'QRBatch')

    qr_media_path = os.path.join(settings.MEDIA_ROOT, 'qrcodes')

    if not os.path.exists(qr_media_path):
        print(f"QR codes directory not found: {qr_media_path}")
        return

    created_count = 0

    for batch_dir in os.listdir(qr_media_path):
        batch_path = os.path.join(qr_media_path, batch_dir)

        if not os.path.isdir(batch_path):
            continue

        # Map directory name to batch name (BatchA -> Batch A)
        if batch_dir.startswith('Batch') and len(batch_dir) == 6:
            batch_letter = batch_dir[-1]
            batch_name = f"Batch {batch_letter}"
        else:
            continue

        try:
            batch = QRBatch.objects.get(batch_name=batch_name)
        except QRBatch.DoesNotExist:
            continue

        for filename in os.listdir(batch_path):
            if not filename.endswith('.png'):
                continue

            token = filename[:-4]  # Remove .png

            # Parse table info from token
            match = re.match(r'xclv-(\w+)-(\d+)-', token)
            if not match:
                continue

            table_type = match.group(1)
            table_number = int(match.group(2))
            qr_hash = hashlib.sha256(token.encode('utf-8')).hexdigest()

            # Create QR code record
            QRCode.objects.create(
                unique_token=token,
                qr_hash=qr_hash,
                table_type=table_type,
                table_number=table_number,
                batch=batch,
                image=f"qrcodes/{batch_dir}/{filename}"
            )

            created_count += 1

    print(f"Created {created_count} QR codes from media files")

class Migration(migrations.Migration):
    dependencies = [
        ('qr_codes', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_qr_codes_from_media),
    ]
