# Generated by Django 5.2.7 on 2025-10-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0002_auto_20251022_0951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='qrbatch',
            options={},
        ),
        migrations.RemoveField(
            model_name='qrbatch',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='qr_hash',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='table_number',
        ),
        migrations.RemoveField(
            model_name='qrcode',
            name='table_type',
        ),
        migrations.AddField(
            model_name='qrbatch',
            name='batch_status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ValidationAttempt',
        ),
    ]
