# Generated by Django 5.2.7 on 2025-10-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_codes', '0003_alter_qrbatch_options_remove_qrbatch_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='qr_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
