# Generated by Django 5.2.7 on 2025-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('total_payment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data', models.JSONField()),
            ],
        ),
    ]
