# Generated by Django 4.2.25 on 2025-10-22 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("category", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
