# Generated by Django 4.2.25 on 2025-12-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_remove_item_item_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.TextField(),
        ),
    ]
