# Generated by Django 4.2.30 on 2026-05-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_alter_item_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
    ]
