# Generated by Django 5.2.7 on 2025-10-31 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tables', '0004_remove_tableorder_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tables.tableorder'),
        ),
    ]
